#config branche
spring:
  cloud:
    config:
      label:                                            rentes-service
# config uri
      uri:                                              http://localhost:8100/config


eureka:
  client:
    serviceUrl:
      defaultZone:      http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry:      true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true