server:
  port:                     8210
  servlet:
    context-path: /gateway

spring:
  application:
      name:                                               spring-gateway
  cloud:
    gateway:
      routes:
       - id: personnes-service-v2
        uri: http://localhost:9012
        predicates:
        - Header=X-migration, 1
        - Path=/personnes/**
        - Weight=per1, 20
        filters:
          - StripPrefix=1
          
      - id: personnes-service
        uri: lb://personnes-service
        predicates:
        - Path=/personnes/**
        - Weight=per1, 80
        filters:
          - StripPrefix=1

      
          
      - id: rentes-service
        uri: lb://rentes-service
        predicates:
        - Path=/rentes/**
        filters:
          - StripPrefix=1

      metrics:
        enabled: true





management:

  endpoint:
    metrics:
      enabled: true

    prometheus:
      enabled: true

  metrics:
    export:
      prometheus:
        enabled: true

  endpoints:

    web:
      exposure:
        include: "*"
    beans:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8300/eureka/


